/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    DefaultTableModel dtm = new DefaultTableModel();
    public NewJFrame() {
        initComponents();
        btnGiai.setEnabled(false);
        btnLamLai.setEnabled(false);
        
        tblPhuongTrinh.setModel(dtm);
        dtm.setColumnIdentifiers(new Object[]{"A","B","C","Nghiem"});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblA = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        txtHeSoA = new javax.swing.JTextField();
        txtHeSoC = new javax.swing.JTextField();
        txtHeSoB = new javax.swing.JTextField();
        lblKetQua = new javax.swing.JLabel();
        btnGiai = new javax.swing.JButton();
        btnLamLai = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        rbBac1 = new javax.swing.JRadioButton();
        rbBac2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhuongTrinh = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GIAI PHUONG TRINH");

        lblA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblA.setText("A");

        lblC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblC.setText("C");

        lblB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblB.setText("B");

        txtHeSoA.setToolTipText("");
        txtHeSoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeSoAActionPerformed(evt);
            }
        });
        txtHeSoA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHeSoAKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHeSoAKeyReleased(evt);
            }
        });

        txtHeSoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeSoCActionPerformed(evt);
            }
        });
        txtHeSoC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHeSoCKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHeSoCKeyReleased(evt);
            }
        });

        txtHeSoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeSoBActionPerformed(evt);
            }
        });
        txtHeSoB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHeSoBKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHeSoBKeyReleased(evt);
            }
        });

        btnGiai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGiai.setText("Giai");
        btnGiai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaiActionPerformed(evt);
            }
        });

        btnLamLai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLamLai.setText("Lam lai");
        btnLamLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamLaiActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThoat.setText("Thoat");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbBac1);
        rbBac1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbBac1.setText("Ax+ B =0");
        rbBac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBac1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbBac2);
        rbBac2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbBac2.setSelected(true);
        rbBac2.setText("Ax^2 + Bx + C=0");
        rbBac2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBac2ActionPerformed(evt);
            }
        });

        tblPhuongTrinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblPhuongTrinh);

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThem.setText("Them");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGiai, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLamLai, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnThem)
                        .addGap(25, 25, 25)
                        .addComponent(btnThoat))
                    .addComponent(lblKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHeSoC, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblA, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHeSoA, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblB, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHeSoB, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbBac1)
                            .addComponent(rbBac2))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHeSoA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHeSoB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHeSoC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(rbBac1)
                        .addGap(18, 18, 18)
                        .addComponent(rbBac2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGiai, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLamLai, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(6, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHeSoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeSoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeSoBActionPerformed

    private void txtHeSoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeSoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeSoAActionPerformed

    private void txtHeSoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeSoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeSoCActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
         System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnGiaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaiActionPerformed
        PhuongTrinh x;
        double a,b,c;
        a = Double.parseDouble(txtHeSoA.getText());
        b = Double.parseDouble(txtHeSoB.getText());
        if(rbBac1.isSelected()){
        x = new PTBac1(a,b);
        }else {
        c = Double.parseDouble(txtHeSoC.getText());
        x =new PTBac2(a,b,c);
        }
        lblKetQua.setText(x.toString());
        btnGiai.setEnabled(false);
        btnLamLai.setEnabled(true);
    }//GEN-LAST:event_btnGiaiActionPerformed

    private void btnLamLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamLaiActionPerformed
         txtHeSoA.setText("");
         txtHeSoB.setText("");
         txtHeSoC.setText("");
         lblKetQua.setText("");
         txtHeSoA.requestFocus();
         btnLamLai.setEnabled(false);
    }//GEN-LAST:event_btnLamLaiActionPerformed

    private void txtHeSoAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHeSoAKeyPressed
        if(isOK())btnGiai.setEnabled(true);
    }//GEN-LAST:event_txtHeSoAKeyPressed

    private void txtHeSoBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHeSoBKeyPressed
        if(isOK())btnGiai.setEnabled(true);
    }//GEN-LAST:event_txtHeSoBKeyPressed

    private void txtHeSoCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHeSoCKeyPressed
       if(isOK())btnGiai.setEnabled(true);
    }//GEN-LAST:event_txtHeSoCKeyPressed

    private void txtHeSoAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHeSoAKeyReleased
        // TODO add your handling code here:
        if(isOK())btnGiai.setEnabled(true);
    }//GEN-LAST:event_txtHeSoAKeyReleased

    private void txtHeSoBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHeSoBKeyReleased
        // TODO add your handling code here:
        if(isOK())btnGiai.setEnabled(true);
    }//GEN-LAST:event_txtHeSoBKeyReleased

    private void txtHeSoCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHeSoCKeyReleased
        // TODO add your handling code here:
        if(isOK())btnGiai.setEnabled(true);
    }//GEN-LAST:event_txtHeSoCKeyReleased

    private void rbBac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBac1ActionPerformed
        // TODO add your handling code here:
        if(rbBac1.isSelected()){
            lblC.setVisible(false);
            txtHeSoC.setVisible(false);
        }
    }//GEN-LAST:event_rbBac1ActionPerformed

    private void rbBac2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBac2ActionPerformed
        // TODO add your handling code here:
        if(rbBac2.isSelected()){
            lblC.setVisible(true);
            txtHeSoC.setVisible(true);
        }
    }//GEN-LAST:event_rbBac2ActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        PhuongTrinh x;
        double a,b,c;
        a = Double.parseDouble(txtHeSoA.getText());
        b = Double.parseDouble(txtHeSoB.getText());
        if(rbBac1.isSelected()){
             x = new PTBac1(a,b);
             dtm.addRow(new Object[]{txtHeSoA.getText(),txtHeSoB.getText(),"",x.giai()});
        }else {
             c = Double.parseDouble(txtHeSoC.getText());
             x =new PTBac2(a,b,c);
             dtm.addRow(new Object[]{txtHeSoA.getText(),txtHeSoB.getText(),txtHeSoC.getText(),x.giai()});
        }
    }//GEN-LAST:event_btnThemActionPerformed
                                  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    public boolean isOK(){
        if(txtHeSoA.getText().equals(""))return false;
        if(txtHeSoB.getText().equals(""))return false;
        if(rbBac2.isSelected()){
        if(txtHeSoC.getText().equals(""))return false;}
        return true ;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiai;
    private javax.swing.JButton btnLamLai;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblKetQua;
    private javax.swing.JRadioButton rbBac1;
    private javax.swing.JRadioButton rbBac2;
    private javax.swing.JTable tblPhuongTrinh;
    private javax.swing.JTextField txtHeSoA;
    private javax.swing.JTextField txtHeSoB;
    private javax.swing.JTextField txtHeSoC;
    // End of variables declaration//GEN-END:variables
}
